// All 28 Indian States + 8 Union Territories
export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  // Union Territories
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

export const SCHEME_CATEGORIES = [
  { id: 'cat_farmer', label: '🌾 Agriculture & Farmer' },
  { id: 'cat_education', label: '🎓 Education & Scholarship' },
  { id: 'cat_health', label: '❤️ Health & Medical' },
  { id: 'cat_employment', label: '💼 Employment & MSME' },
  { id: 'cat_housing', label: '🏠 Housing & Urban Dev' },
  { id: 'cat_identity', label: '🪪 Identity & Certificates' },
  { id: 'cat_transport', label: '🚗 Transport & DL' },
  { id: 'cat_welfare', label: '🧓 Social Welfare & Pension' },
  { id: 'cat_finance', label: '🏦 Finance & Banking' },
  { id: 'cat_legal', label: '⚖️ Legal & Justice' },
];
